### PR TITLE
Creating custom user in Dockerfile

### PR DESCRIPTION
**Pull request by Adrian-99**

### CODE REVIEW

**Comment by mherda64** [comment]
LGTM, you may also add --disable-password flag in adduser

**Comment by Adrian-99** [comment]
> LGTM, you may also add --disable-password flag in adduser

There seems to be no such option (I'm using useradd command, not adduser, if that makes a difference). According to documentation, if --password option is not used (which is the case here) then the password is disabled, so the result should be the same anyways.

**Review by mherda64 — APPROVED** [review]

**Comment by mherda64** [comment]
You may also bump the version in k8s/overlays/dev and build a new image

**Comment by Adrian-99** [comment]
> You may also bump the version in k8s/overlays/dev and build a new image

Done. Changed tag to 0.11 because I think that incrementing version by 0.1 each time would result in reaching 1.0 way too early. Step of 0.01 should be fine I guess.

**Pull request merged**
